<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // const promise = new Promise((resolve, reject) => {
        //     resolve.log('success1');
        //     reject('error');
        //     resolve('success2');
        // });
        // promise.then((res) => {
        //     console.log('then: ', res);
        // }).catch((err) => {
        //     console.log('catch: ', err);
        // });

        // const promise = new Promise((resolve, reject) => {
        //     reject('error');
        //     resolve('success2');
        // });
        // promise.then(res => {
        //     console.log('then1 ', res);
        // }).then(res => {
        //     console.log('then2 ', res);
        // }).catch(err => {
        //     console.log('catch: ', err);
        // }).then(res => {
        //     console.log('then3 ', res);
        // });

        // Promise.resolve(1)
        //     .then(res => {
        //         console.log(res);
        //         return 2
        //     }).catch(err => {
        //         return 3
        //     }).then(res => {
        //         console.log(res)
        //     })
        // //1 2

        // Promise.reject(1)
        //     .then(res => {
        //         console.log(res);
        //         return 2;
        //     })
        //     .catch(err => {
        //         console.log(err);
        //         return 3
        //     })
        //     .then(res => {
        //         console.log(res);
        //     });
        // //1 3

        // const promise = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log('timer');
        //         resolve('success');
        //     }, 1000);
        // });
        // const start = Date.now();
        // promise.then(res => {
        //     console.log(res, Date.now() - start)
        // });
        // promise.then(res => {
        //     console.log(res, Date.now() - start)
        // })
        // 'timer'
        // 'success' 1001
        // 'success' 1002

        // Promise.resolve()
        //     .then(() => {
        //         return new Error('error!!!');
        //     })
        //     .then(res => {
        //         console.log("then: ", res)
        //     })
        //     .catch(err => {
        //         console.log('catch ', err)
        //     })
        //"then: " "Error: error!!!"

        // const promise = Promise.resolve().then(() => {
        //     return promise
        // });
        // promise.catch(console.err)
        // //Uncaught (in promise) TypeError: Chaining cycle detected for promise #<Promise>

        // Promise.resolve(1)
        //     .then(2)
        //     .then(Promise.resolve(3))
        //     .then(console.log)
        // //1

        // Promise.reject('err!!!')
        //     .then(res => {
        //         console.log('success', res)
        //     }, err => {
        //         console.log('error', err)
        //     })
        //     .catch(err => {
        //         console.log('catch', err)
        //     })
        // //error err!!!
        // Promise.reject('err!!!')
        //     .then((res) => {
        //         console.log('success', res)
        //     }).catch(err => {
        //         console.log('catch', err)
        //     })
        // //catch err!!!
        // Promise.resolve()
        //     .then(function success(res) {
        //         throw new Error('error!!!')
        //     }, function fail1(err) {
        //         console.log('fail1', err)
        //     })
        //     .catch(function fail2(err) {
        //         console.log('fail1', err)
        //     })
        // //fail1 Error: error!!!

        Promise.resolve('1')
            .then(res => {
                console.log(res)
            })
            .finally(() => {
                console.log('finally')
            })
        Promise.resolve('2')
            .finally(() => {
                console.log('finally2');
                return '我是finally2返回的值'
            })
            .then(res => {
                console.log('finally2后面的then函数', res)
            })
        //'1' finally2' 'finally' 'finally2后面的then函数' '2'

        function promise1() {
            let p = new Promise(resolve => {
                console.log('promisw1');
                resolve('1')
            });
            return p;
        }
        function promise2() {
            return new Promise((resolve, reject) => {
                reject('error')
            })
        }
        promise1()
            .then(res => { console.log(res) })
            .catch(err => { console.log(err) })
            .finally(() => { console.log('finally1') });
        promise2()
            .then(res => { console.log(res) })
            .catch(err => { console.log(err) })
            .finally(() => { console.log(finally2) })
        //'promise1' '1' 'error' 'finally1' 'finally2'
    </script>
</body>

</html>